# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hired', models.DateTimeField(verbose_name='Hired Date')),
                ('date_last', models.DateTimeField(verbose_name='Last Day of Work')),
                ('name_employer', models.CharField(max_length=200, verbose_name='Employer')),
                ('website_employer', models.CharField(max_length=200, verbose_name='Employer  Website')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_name', models.CharField(max_length=200, verbose_name='Preferred Prefix')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('suffix_name', models.CharField(max_length=200, verbose_name='Suffix')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('about', models.TextField(verbose_name='About Me')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('endorsement', models.CharField(max_length=200)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byronplee.Employer')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='byronplee.Person'),
        ),
    ]
