# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='Current, Home, Mailing, etc.')),
                ('line1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='City')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('zip', models.CharField(max_length=5, verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_number', models.IntegerField(verbose_name='Author Number')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary_name', models.CharField(blank=True, max_length=200, verbose_name='commentary_name')),
                ('commentary_link', models.URLField(blank=True, verbose_name='commentary_link')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_work', models.TextField(blank=True, verbose_name='current_work')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(blank=True, max_length=200, verbose_name='date_range')),
                ('degree_type', models.CharField(blank=True, max_length=200, verbose_name='degree_type')),
                ('major', models.CharField(blank=True, max_length=200, verbose_name='major')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='institution')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='F1000',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F1000_name', models.CharField(blank=True, max_length=200, verbose_name='F1000_name')),
                ('F1000_link', models.URLField(blank=True, verbose_name='F1000_link')),
            ],
        ),
        migrations.CreateModel(
            name='FormerAffiliations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(blank=True, max_length=200, verbose_name='date_range')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='position')),
                ('supervisor', models.CharField(blank=True, max_length=200, verbose_name='supervisor')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='institution')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='KVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('active', models.BooleanField()),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('position_title', models.CharField(blank=True, max_length=200, verbose_name='position_title')),
                ('start_date', models.DateField(blank=True, verbose_name='start_date')),
                ('pi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtherPublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_publications', models.TextField(blank=True, verbose_name='list_of_publications')),
                ('lab_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.LabMember')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='title')),
                ('abstract', models.TextField(blank=True, verbose_name='abstract')),
                ('pubdate', models.DateField(blank=True, verbose_name='publication date')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='journal title')),
                ('volume', models.CharField(blank=True, max_length=200, verbose_name='volume')),
                ('details', models.CharField(blank=True, max_length=200, verbose_name='details')),
                ('pagination', models.CharField(blank=True, max_length=200, verbose_name='pagination')),
                ('page_start', models.CharField(blank=True, max_length=10, verbose_name='first page')),
                ('page_end', models.CharField(blank=True, max_length=10, verbose_name='last page')),
                ('pdf', models.FileField(blank=True, upload_to='paper')),
                ('googlescholar', models.URLField(blank=True, verbose_name='link to google scholar')),
                ('pubmed', models.URLField(blank=True, verbose_name='link to pubmed')),
                ('PMID', models.CharField(blank=True, max_length=10, verbose_name='PMID')),
                ('DOI', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('publicationlink', models.URLField(blank=True, verbose_name='direct link to publication')),
                ('eID', models.CharField(blank=True, max_length=10, verbose_name='eID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('initials', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Research_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_content_summary', models.CharField(blank=True, max_length=255)),
                ('topic_content', models.TextField(blank=True, verbose_name='topic_content')),
                ('content_number', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Research_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_image_tag', models.CharField(blank=True, max_length=255)),
                ('topic_image', models.ImageField(blank=True, upload_to='research_page_images')),
                ('image_number', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Research_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, verbose_name='heading')),
                ('research_summary_number', models.CharField(blank=True, max_length=3)),
                ('content', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='labwebsite.Research_Content')),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='labwebsite.Research_Image')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(blank=True, verbose_name='interests')),
                ('lab_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.LabMember')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='website name')),
                ('url', models.URLField(blank=True, verbose_name='link to website')),
                ('lab_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.LabMember')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(through='labwebsite.Authorship', to='labwebsite.Person'),
        ),
        migrations.AddField(
            model_name='labmember',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.Person'),
        ),
        migrations.AddField(
            model_name='formeraffiliations',
            name='lab_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.LabMember'),
        ),
        migrations.AddField(
            model_name='f1000',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.Paper'),
        ),
        migrations.AddField(
            model_name='education',
            name='lab_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.LabMember'),
        ),
        migrations.AddField(
            model_name='currentwork',
            name='lab_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.LabMember'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.Paper'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.Paper'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='lab_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labwebsite.LabMember'),
        ),
    ]
